services:
  couchbase:
    image: couchbase/server:community-7.6.2
    container_name: url-shortener-couchbase
    ports:
      - "8091-8097:8091-8097"
      - "11210-11211:11210-11211"
    volumes:
      - couchbase-data:/opt/couchbase/var

  redis:
    image: redis:7.4-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  couchbase-data:
  redis-data:
